pub fn dis() {
    match inst {
        0x00 => self.brk(inst),
        0x01 => self.ora(inst),
        0x05 => self.ora(inst),
        0x06 => self.asl(inst),
        0x08 => self.php(inst),
        0x09 => self.ora(inst),
        0x0a => self.asl(inst),
        0x0d => self.ora(inst),
        0x0e => self.asl(inst),

        0x10 => self.bpl(inst),
        0x11 => self.ora(inst),
        0x15 => self.ora(inst),
        0x16 => self.asl(inst),
        0x18 => self.clc(inst),
        0x19 => self.ora(inst),
        0x1d => self.ora(inst),
        0x1e => self.asl(inst),

        0x20 => self.jsr(inst),
        0x21 => self.and(inst),
        0x24 => self.bit(inst),
        0x25 => self.and(inst),
        0x26 => self.rol(inst),
        0x28 => self.plp(inst),
        0x29 => self.and(inst),
        0x2a => self.rol(inst),
        0x2c => self.bit(inst),
        0x2d => self.and(inst),
        0x2e => self.rol(inst),

        0x30 => self.bmi(inst),
        0x31 => self.and(inst),
        0x35 => self.and(inst),
        0x36 => self.rol(inst),
        0x38 => self.sec(inst),
        0x39 => self.and(inst),
        0x3d => self.and(inst),
        0x3e => self.rol(inst),

        0x40 => self.rti(inst),
        0x41 => self.eor(inst),
        0x45 => self.eor(inst),
        0x46 => self.lsr(inst),
        0x48 => self.pha(inst),
        0x49 => self.eor(inst),
        0x4a => self.lsr(inst),
        0x4c => self.jmp(inst),
        0x4d => self.eor(inst),
        0x4e => self.lsr(inst),

        0x50 => self.bvc(inst),

        0x51 => self.eor(inst),
        0x55 => self.eor(inst),
        0x56 => self.lsr(inst),
        0x58 => self.cli(inst),
        0x59 => self.eor(inst),
        0x5d => self.eor(inst),
        0x5e => self.lsr(inst),

        0x60 => self.rts(inst),
        0x61 => self.adc(inst),
        0x65 => self.adc(inst),
        0x66 => self.ror(inst),
        0x68 => self.pla(inst),
        0x69 => self.adc(inst),
        0x6a => self.ror(inst),
        0x6c => self.jmp_ind(inst),
        0x6d => self.adc(inst),
        0x6e => self.ror(inst),

        0x70 => self.bvs(inst),
        0x71 => self.adc(inst),
        0x75 => self.adc(inst),
        0x76 => self.ror(inst),
        0x78 => self.sei(inst),
        0x79 => self.adc(inst),
        0x7d => self.adc(inst),
        0x7e => self.ror(inst),

        0x81 => self.sta(inst),
        0x84 => self.sty(inst),
        0x85 => self.sta(inst),
        0x86 => self.stx(inst),
        0x88 => self.dey(inst),
        0x8a => self.txa(inst),
        0x8c => self.sty(inst),
        0x8d => self.sta(inst),
        0x8e => self.stx(inst),

        0x90 => self.bcc(inst),
        0x91 => self.sta(inst),
        0x94 => self.sty(inst),
        0x95 => self.sta(inst),
        0x96 => self.stx(inst),
        0x98 => self.tya(inst),
        0x99 => self.sta(inst),
        0x9a => self.txs(inst),
        0x9d => self.sta(inst),

        0xa0 => self.ldy(inst),
        0xa1 => self.lda(inst),
        0xa2 => self.ldx(inst),
        0xa4 => self.ldy(inst),
        0xa5 => self.lda(inst),
        0xa6 => self.ldx(inst),
        0xa8 => self.tay(inst),
        0xa9 => self.lda(inst),
        0xaa => self.tax(inst),
        0xac => self.ldy(inst),
        0xad => self.lda(inst),
        0xae => self.ldx(inst),

        0xb0 => self.bcs(inst),
        0xb1 => self.lda(inst),
        0xb4 => self.ldy(inst),
        0xb5 => self.lda(inst),
        0xb6 => self.ldx(inst),

        0xb8 => self.clv(inst),
        0xb9 => self.lda(inst),
        0xba => self.tsx(inst),
        0xbc => self.ldy(inst),
        0xbd => self.lda(inst),
        0xbe => self.ldx(inst),

        0xc0 => self.cpy(inst),
        0xc1 => self.cmp(inst),
        0xc4 => self.cpy(inst),
        0xc5 => self.cmp(inst),
        0xc6 => self.dec(inst),
        0xc8 => self.iny(inst),
        0xc9 => self.cmp(inst),
        0xca => self.dex(inst),
        0xcc => self.cpy(inst),
        0xcd => self.cmp(inst),
        0xce => self.dec(inst),

        0xd0 => self.bne(inst),
        0xd1 => self.cmp(inst),
        0xd5 => self.cmp(inst),
        0xd6 => self.dec(inst),
        0xd8 => self.cld(inst),
        0xd9 => self.cmp(inst),
        0xdd => self.cmp(inst),
        0xde => self.dec(inst),

        0xe0 => self.cpx(inst),
        0xe1 => self.sbc(inst),
        0xe4 => self.cpx(inst),
        0xe5 => self.sbc(inst),
        0xe6 => self.inc(inst),
        0xe8 => self.inx(inst),
        0xe9 => self.sbc(inst),
        0xea => self.nop(inst),
        0xec => self.cpx(inst),
        0xed => self.sbc(inst),
        0xee => self.inc(inst),

        0xf0 => self.beq(inst),
        0xf1 => self.sbc(inst),
        0xf5 => self.sbc(inst),
        0xf6 => self.inc(inst),
        0xf8 => self.sed(inst),
        0xf9 => self.sbc(inst),
        0xfd => self.sbc(inst),
        0xfe => self.inc(inst),
    }
}
// _ => assert!(false, "Unknown instruction {:02X}", inst),
